StumpScore/Areas/Admin/Controllers/PlayerController.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vispl.Trainee.StumpScore.BL;
using Vispl.Trainee.StumpScore.VO.Enums;
using Vispl.Trainee.StumpScore.VO.Models;

namespace StumpScore.Areas.Admin.Controllers
{
    public class PlayerController : Controller
    {
        private readonly PlayerService _playerService;
        private readonly CountryService _countryService;
        private readonly PlayerTypeService _playerTypeService;
        public PlayerController()
        {
            _playerService = new PlayerService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _countryService = new CountryService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _playerTypeService = new PlayerTypeService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
        }

        // ------------------ players main page dashboard
        public ActionResult Index()
        {
            List<Player> players = _playerService.GetAll();
            return View(players);
        }
        // ------------------ create player page [HttpGet]
        public ActionResult Create()
        {
            // ----- getting all countries
            List<Country> Countries = _countryService.GetAll();
            List<SelectListItem> CountriesList = Countries.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.CountryName
            }).ToList();
            ViewBag.Countries = CountriesList;

            // ----- getting all tournamnets type
            List<PlayerType> playerTypes = _playerTypeService.GetAll();
            List<SelectListItem> playerTypeList = playerTypes.Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.TypeName
            }).ToList();
            ViewBag.PlayersType = playerTypeList;
            return View();
        }
        // ------------------ create player page [HttpPost]
        [HttpPost]
        public ActionResult Create(Player player, List<HttpPostedFileBase> playerImage)
        {
            if (player.CountryId == 0 || player.PlayerTypeId == 0)
            {
                if (player.CountryId == 0)
                {
                    ModelState.AddModelError("CountryId", "country is required");
                }
                if (player.CountryId == 0)
                {
                    ModelState.AddModelError("PlayerTypeId", "Player Type is required");
                }               
            }
            // ----- if model is valid
            if (ModelState.IsValid)
            {
                // -----storing the player picture if provided
                if (playerImage != null && (playerImage.Count > 1 || playerImage[0] != null))
                {
                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(playerImage[1].FileName);
                    string path = Path.Combine(Server.MapPath("~/Content/Images/Players"), fileName);
                    playerImage[1].SaveAs(path);
                    player.Picture = Path.Combine("/Content/Images/Players", fileName);
                }
                else
                {
                    ModelState.AddModelError("Picture", "player image is required");
                    return View(player);
                }
                // ----- if player added successfully
                if (_playerService.Add(player))
                {
                    return RedirectToAction("Index");
                }
                // ----- if player is not added successfully
                else
                {
                    return View(player);
                }
            }
            // ----- if model is not valid
            else
            {
                if (player.CountryId == 0 || player.PlayerTypeId == 0)
                {
                    if (player.CountryId == 0)
                    {
                        ModelState.AddModelError("CountryId", "country is required");
                    }
                    if (player.CountryId == 0)
                    {
                        ModelState.AddModelError("PlayerTypeId", "Player Type is required");
                    }
                    //return View(player);
                }
                // ----- getting all countries
                List<Country> Countries = _countryService.GetAll();
                List<SelectListItem> CountriesList = Countries.Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.CountryName
                }).ToList();
                ViewBag.Countries = CountriesList;
                // ----- getting all tournamnets type
                List<PlayerType> playerTypes = _playerTypeService.GetAll();
                List<SelectListItem> playerTypeList = playerTypes.Select(c => new SelectListItem
                {
                    Value = c.Id.ToString(),
                    Text = c.TypeName
                }).ToList();
                ViewBag.PlayersType = playerTypeList;
                return View(player);
            }
        }
    }
}

StumpScore/Areas/Admin/Views/Player/Create.cshtml
@model Vispl.Trainee.StumpScore.VO.Models.Player
@{
    ViewBag.Title = "Create Player";
}
<style>
    #playerContainer {
        width: 70vw;
        margin: 10px auto;
    }

        #playerContainer input {
            border: none;
            outline: none;
        }
</style>
<div id="playerContainer">
    <div>
        <h2 class="text-center">Create Player</h2>
    </div>
    <div>
        @using (Html.BeginForm("Create", "Player", FormMethod.Post, new { enctype = "multipart/form-data", @id = "playerForm" }))
        {
            // ----------------- Name
            <div>
                @Html.LabelFor(m => m.Name)
                <span class="required">*</span>
                <br />
                @Html.EJS().TextBoxFor(m => m.Name).Placeholder("Enter Name").Render()
                <br />
                @Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" })
            </div>
            // ----------------- Jersey number
            <div>
                @Html.LabelFor(m => m.JerseyNumber)
                <span class="required">*</span>
                <br />
                @Html.EJS().NumericTextBoxFor(m => m.JerseyNumber).Format("###").Placeholder("Enter Jersey number").Render()
                <br />
                @Html.ValidationMessageFor(m => m.JerseyNumber, null, new { @class = "text-danger" })
            </div>
            // ----------------- date Of birth
            <div>
                @Html.LabelFor(m => m.DateOfBirth)
                <span class="required">*</span>
                <br />
                @Html.EJS().DatePickerFor(m => m.DateOfBirth).Placeholder("Enter Date of Birth").Render()
                <br />
                @Html.ValidationMessageFor(m => m.DateOfBirth, null, new { @class = "text-danger" })
            </div>
            // ----------------- Age
            <div>
                @Html.DisplayNameFor(m => m.Age)
                <span class="required">*</span>
                <br />
                @Html.EJS().TextBoxFor(m => m.Age).Placeholder("Enter age").Render()
                <br />
                @Html.ValidationMessageFor(m => m.Age, null, new { @class = "text-danger" })
            </div>
            // ----------------- Birth Place
            <div>
                @Html.DisplayNameFor(m => m.BirthPlace)
                <br />
                @Html.EJS().TextBoxFor(m => m.BirthPlace).Placeholder("Enter birth place").Render()
                <br />
                @Html.ValidationMessageFor(m => m.BirthPlace, null, new { @class = "text-danger" })

            </div>
            // ----------------- Nationality (Country)
            <div>
                @Html.DisplayNameFor(m => m.CountryId)
                <span class="required">*</span>
                <br />
                @Html.EJS().DropDownListFor(m => m.CountryId).DataSource(ViewBag.Countries as IEnumerable<SelectListItem>).Fields(f => f.Text("Text").Value("Value")).Placeholder("select country").Render()
                <br />
                @Html.ValidationMessageFor(m => m.CountryId, null, new { @class = "text-danger" })
            </div>
            // ----------------- Player Type
            <div>
                @Html.DisplayNameFor(m => m.PlayerTypeId)
                <span class="required">*</span>
                <br />
                @Html.EJS().DropDownListFor(m => m.PlayerTypeId).DataSource(ViewBag.PlayersType as IEnumerable<SelectListItem>).Fields(f => f.Text("Text").Value("Value")).Placeholder("Select Player Type").Render()
                <br />
                @Html.ValidationMessageFor(m => m.PlayerTypeId, null, new { @class = "text-danger" })
            </div>
            // ----------------- Is Captain
            <div>
                @Html.EJS().CheckBoxFor(m => m.IsCaptain).Label("Play as Captain").Render()
                <br />
                @Html.ValidationMessageFor(m => m.IsCaptain, null, new { @class = "text-danger" })
            </div>
            // ----------------- total matches played
            <div>
                @Html.DisplayNameFor(m => m.MatchesPlayed)
                <br />
                @Html.EJS().TextBoxFor(m => m.MatchesPlayed).Placeholder("Total matches played count").Render()
                <br />
                @Html.ValidationMessageFor(m => m.MatchesPlayed, null, new { @class = "text-danger" })
            </div>
            // ----------------- total runs scored
            <div>
                @Html.DisplayNameFor(m => m.RunsScored)
                <br />
                @Html.EJS().TextBoxFor(m => m.RunsScored).Placeholder("Total runs scored").Render()
                <br />
                @Html.ValidationMessageFor(m => m.RunsScored, null, new { @class = "text-danger" })
            </div>
            // ----------------- total wicket taken
            <div>
                @Html.DisplayNameFor(m => m.WicketTaken)
                <br />
                @Html.EJS().TextBoxFor(m => m.WicketTaken).Placeholder("Total wickets taken").Render()
                <br />
                @Html.ValidationMessageFor(m => m.WicketTaken, null, new { @class = "text-danger" })
            </div>
            // ----------------- batting average
            <div>
                @Html.DisplayNameFor(m => m.BattingAverage)
                <br />
                @Html.EJS().TextBoxFor(m => m.BattingAverage).Type("number").Placeholder("Enter batting average").Render()
                <br />
                @Html.ValidationMessageFor(m => m.BattingAverage, null, new { @class = "text-danger" })
            </div>
            // ----------------- bowling average
            <div>
                @Html.DisplayNameFor(m => m.BowlingAverage)
                <br />
                @Html.EJS().TextBoxFor(m => m.BowlingAverage).Type("number").Placeholder("Enter bowling average").Render()
                <br />
                @Html.ValidationMessageFor(m => m.BowlingAverage, null, new { @class = "text-danger" })
            </div>
            // ----------------- Centuries
            <div>
                @Html.DisplayNameFor(m => m.Centuries)
                <br />
                @Html.EJS().TextBoxFor(m => m.Centuries).Type("number").Placeholder("Enter total centuries").Render()
                <br />
                @Html.ValidationMessageFor(m => m.Centuries, null, new { @class = "text-danger" })
            </div>
            // ----------------- Half Centuries
            <div>
                @Html.DisplayNameFor(m => m.HalfCenturies)
                <br />
                @Html.EJS().TextBoxFor(m => m.HalfCenturies).Type("number").Placeholder("Enter total half centuries").Render()
                <br />
                @Html.ValidationMessageFor(m => m.HalfCenturies, null, new { @class = "text-danger" })
            </div>
            // ----------------- Debut Date
            <div>
                @Html.DisplayNameFor(m => m.DebutDate)
                <br />
                @Html.EJS().DatePickerFor(m => m.DebutDate).Placeholder("Enter Debut date").Render()
                <br />
                @Html.ValidationMessageFor(m => m.DebutDate, null, new { @class = "text-danger" })
            </div>
            // ----------------- ICC Ranking
            <div>
                @Html.DisplayNameFor(m => m.ICCRanking)
                <br />
                @Html.EJS().TextBoxFor(m => m.ICCRanking).Type("number").Placeholder("Enter ICC Ranking").Render()
                <br />
                @Html.ValidationMessageFor(m => m.ICCRanking, null, new { @class = "text-danger" })
            </div>
            // ----------------- Picture
            <div>
                @Html.DisplayNameFor(m => m.Picture)
                <span class="required">*</span>
                <br />
                @Html.EJS().Uploader("playerImage").Multiple(false).Render()
                @*@Html.TextBox("file", "", new { type = "file", required = "required" })*@
                <br />
                @Html.ValidationMessageFor(m => m.Picture, null, new { @class = "text-danger" })
            </div>
            <div>
                <div>
                    <input type="submit" />
                </div>
                <div>
                    <a href="#" onclick="alert('Not implemented');">Clear</a>
                </div>
                <div>
                    @Html.ActionLink("Go to players list", "Index", "Player", new { area = "Admin" })
                </div>
            </div>
        }
    </div>
</div>

StumpScore/Areas/Admin/Views/Player/Index.cshtml
@model List<Vispl.Trainee.StumpScore.VO.Models.Player>
@{
    ViewBag.Title = "All Players";
}
@functions{
    public string GetImageLocation(string playerType)
    {
        return "";
    }
}
<style>
    #PlayerContainer {
        padding: 2rem;
    }

    .image img {
        height: 55px;
        width: 55px;
        border-radius: 50px;
        box-shadow: inset 0 0 1px #e0e0e0, inset 0 0 14px rgba(0, 0, 0, 0.2);
    }

    .playerTypeImage {
        width: 25px;
        height: 25px;
    }

</style>
<script>
    function recordClick(args) {
        console.log(args);
    }
</script>
<div id="PlayerContainer">
    <div>
        <h2 class="text-center">All Players</h2>
        <div>
            @Html.ActionLink("Create new", "Create", "Player", new { @class = "createBtn" })
        </div>
    </div>
    <div>
        @Html.EJS().Grid("grid").DataSource(Model).Columns(col =>
    {
        col.Field("Name").HeaderText("Player").Template("#playerInfo").HeaderTextAlign(Syncfusion.EJ2.Grids.TextAlign.Center).Width("250").Add();
        col.Field("Nationality.CountryFlag").HeaderText("Country").Template(" <img src=${Nationality.CountryFlag} height='30px'/>").Add();
        col.Field("DateOfBirth").HeaderText("Date Of Birth").Format("yMd").Add();
        col.Field("MatchesPlayed").HeaderText("Total Matches").Add();
        col.Field("RunsScored").HeaderText("Total Runs").Add();
        col.Field("WicketTaken").HeaderText("Total Wickets").Add();
        col.Field("BattingAverage").HeaderText("Batting Average").Add();
        col.Field("BowlingAverage").HeaderText("Batting Average").Add();

        col.Field("100/50").HeaderText("100/50").Template("#centuriesHalfCenturies").Add();

    }).AllowPaging(true).PageSettings(p =>
    {
        p.PageSize(6);
    }).AllowFiltering().Render()
    </div>
</div>

<script id="playerInfo" type="text/x-template">
    <div>
        <span class="image">
            <img src="${Picture}" alt="" />
        </span>
        <span>${Name}</span>
        <span>(${JerseyNumber})</span>
        <span>
            <img class="playerTypeImage" src="../../../../Content/Images/PlayersType/${PlayerType.TypeName}.png" />
        </span>
    </div>
</script>
<script id="centuriesHalfCenturies" type="text/x-template">
    <div>
        <span>${Centuries}/${HalfCenturies}</span>
    </div>
</script>