StumpScore/Areas/Admin/Controllers/MatchController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Vispl.Trainee.StumpScore.BL;
using Vispl.Trainee.StumpScore.VO.Models;

namespace StumpScore.Areas.Admin.Controllers
{
    public class MatchController : Controller
    {
        private readonly TeamService _teamService;
        private readonly MatchService _matchService;
        private readonly StadiumService _stadiumService;
        private readonly TournamentService _tournamentService;
        private readonly PlayerMatchService _playerMatchService;
        private readonly BallStatsService _ballStatsService;
        private readonly PlayerService _playerService;
        public MatchController()
        {
            _teamService = new TeamService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _matchService = new MatchService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _stadiumService = new StadiumService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _tournamentService = new TournamentService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _playerMatchService = new PlayerMatchService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _ballStatsService = new BallStatsService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _playerService = new PlayerService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
        }
        // ------------------ match page dashboard
        public ActionResult Index()
        {
            List<Tournament> tournaments = _tournamentService.GetAll();
            return View(tournaments);
        }
        // ------------------ match create [HttpGet]
        public ActionResult Create()
        {
            List<Team> teams = _teamService.GetAll();
            List<SelectListItem> teamsList = teams.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name,
            }).ToList();
            ViewBag.Teams = teamsList;
            List<Stadium> stadiums = _stadiumService.GetAll();
            ViewBag.Stadiums = stadiums;
            List<SelectListItem> tournaments = _tournamentService.GetAll().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name,
            }).ToList();
            ViewBag.Tournaments = tournaments;
            return View();
        }
        // ------------------ match create [HttpPost]
        [HttpPost]
        public ActionResult Create(Matches match)
        {
            if (match.StadiumId == 0)
            {
                ModelState.AddModelError("StadiumId", "Stadium is required");
            }
            if (match.Team1Id == 0)
            {
                ModelState.AddModelError("Team1Id", "Stadium is required");
            }
            if (match.Team2Id == 0)
            {
                ModelState.AddModelError("Team2Id", "Stadium is required");
            }
            if (match.TournamentId == 0)
            {
                ModelState.AddModelError("TournamentId", "Tournament is required");
            }
            if (ModelState.IsValid)
            {
                if (_matchService.Add(match))
                {
                    return RedirectToAction("Index");
                }
            }
            // --------------- if model state is not valid
            List<Team> teams = _teamService.GetAll();
            List<SelectListItem> teamsList = teams.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name,
            }).ToList();
            ViewBag.Teams = teamsList;
            List<Stadium> stadiums = _stadiumService.GetAll();
            ViewBag.Stadiums = stadiums;
            List<SelectListItem> tournaments = _tournamentService.GetAll().Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name,
            }).ToList();
            ViewBag.Tournaments = tournaments;
            return View(match);
        }

        // ---------- getting all tournaments
        public ActionResult MatchesForTournament(int tournamentId)
        {
            List<Matches> matchList = _matchService.GetMatchForTournament(tournamentId);
            return PartialView("_Matches", matchList);
        }
        // -------- getting detailed view of a match
        public ActionResult MatchDetailedSummary(int matchId, int tournamentId)
        {
            Matches match = _matchService.GetMatch(matchId);
            MatchDetailedVM matchDetailedVM = new MatchDetailedVM();

            Team team1 = _teamService.Get(match.Team1Id);
            team1.Players = _playerMatchService.GetPlayersForMatch(match.Team1Id, tournamentId);

            Team team2 = _teamService.Get(match.Team2Id);
            team2.Players = _playerMatchService.GetPlayersForMatch(match.Team2Id, tournamentId);

            matchDetailedVM.Team1 = team1;
            matchDetailedVM.Team2 = team2;
            matchDetailedVM.MatchStart = match.MatchStart;
            matchDetailedVM.MatchEnd = match.MatchEnd;
            matchDetailedVM.Stadium = _stadiumService.Get(match.StadiumId);
            return View(matchDetailedVM);
        }
        public ActionResult StartTheMatch(int matchId, int tournamentId)
        {
            Matches match = _matchService.GetMatch(matchId);
            if (match.TossWonBy > 0)
            {
                return RedirectToAction("LiveMatchHandler", new { matchId = matchId, tournamentId = tournamentId });
            }
            else
            {
                Team team1 = _teamService.Get(match.Team1Id);
                Team team2 = _teamService.Get(match.Team2Id);

                match.Team1 = team1;
                match.Team2 = team2;
                return View(match);
            }
        }
        [HttpPost]
        public ActionResult StartTheMatch(Matches match, int toss, string choosenOption)
        {
            _matchService.UpdateToss(match, toss, choosenOption);
            return RedirectToAction("LiveMatchHandler", new { matchId = match.Id, tournamentId = match.TournamentId });
        }
        public ActionResult LiveMatchHandler(int matchId, int tournamentId)
        {
            // -------------------------- creating view for the live match
            LiveMatchHandlerVO liveMatchHandlerVO = new LiveMatchHandlerVO();
            Matches match = _matchService.GetMatch(matchId);
            match.TournamentId = tournamentId;
            match.Tournament = _tournamentService.GetAll().Where(t => t.Id == match.TournamentId).FirstOrDefault();

            Team team1 = _teamService.Get(match.Team1Id);
            team1.Players = _playerMatchService.GetPlayersForMatch(match.Team1Id, tournamentId);

            Team team2 = _teamService.Get(match.Team2Id);
            team2.Players = _playerMatchService.GetPlayersForMatch(match.Team2Id, tournamentId);

            match.Team1 = team1;
            match.Team2 = team2;

            match.Stadium = _stadiumService.Get(match.StadiumId);
            liveMatchHandlerVO.Matches = match;
            // --------------- extras in inning 1
            List<BallStats> ballStats = _ballStatsService.GetAll(matchId, tournamentId, 1);
            StringBuilder extras = new StringBuilder();
            int extraTotal = 0;
            foreach (BallStats ballStat in ballStats)
            {
                if (ballStat.Extras.Length > 0)
                {
                    if (ballStat.Extras == "wide")
                    {
                        extras.Append(ballStat.Runs + "(wd)");
                    }
                    else if (ballStat.Extras == "NoBall")
                    {
                        extras.Append(ballStat.Runs + "(nb)");
                    }
                    extraTotal += ballStat.Runs;
                    extraTotal += 1;
                }
            }
            Inning inning1 = new Inning();
            inning1.Extras = extras.ToString();
            inning1.ExtrasRuns = extraTotal;
            liveMatchHandlerVO.Inning1 = inning1;

            // ------------- extras in Inning 2
            ballStats = _ballStatsService.GetAll(matchId, tournamentId, 1);
            extras.Clear();
            extraTotal = 0;
            foreach (BallStats ballStat in ballStats)
            {
                if (ballStat.Extras.Length > 0)
                {
                    if (ballStat.Extras == "wide")
                    {
                        extras.Append(ballStat.Runs + "(wd)");
                    }
                    else if (ballStat.Extras == "NoBall")
                    {
                        extras.Append(ballStat.Runs + "(nb)");
                    }
                    extraTotal += ballStat.Runs;
                    extraTotal += 1;
                }
            }
            Inning inning2 = new Inning();
            inning1.Extras = extras.ToString();
            liveMatchHandlerVO.Inning2 = inning2;

            // --------------- batsman stats for the inning
            for (int i = 0; i < liveMatchHandlerVO.Matches.Team1.Players.Count; i++)
            {
                Player player = liveMatchHandlerVO.Matches.Team1.Players[i];
                player.RunsScored = ballStats.Where(b => b.OnStrike == player.Id && b.Extras.Length == 0).Sum(b => b.Runs);
                player.BallPlayed = ballStats.Where(b => b.OnStrike == player.Id && b.Extras.Length > 0).Count();

StumpScore/Areas/Admin/Controllers/TeamController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vispl.Trainee.StumpScore.BL;
using Vispl.Trainee.StumpScore.VO.Models;

namespace StumpScore.Areas.Admin.Controllers
{
    public class TeamController : Controller
    {
        private readonly PlayerService _playerService;
        private readonly TeamService _teamService;
        private readonly TournamentService _tournamentService;
        private readonly PlayerMatchService _playerMatchService;
        public TeamController()
        {
            _playerService = new PlayerService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _teamService = new TeamService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _tournamentService = new TournamentService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _playerMatchService = new PlayerMatchService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
        }
        // ------------------ Team main page dashboard
        public ActionResult Index()
        {
            List<Team> teams = _teamService.GetAll();
            foreach(var team in teams)
            {
                team.Captain = _playerService.GetAll().Where(p => p.Id == team.CaptainId).FirstOrDefault();
                team.ViceCaptain = _playerService.GetAll().Where(p => p.Id == team.ViceCaptainId).FirstOrDefault();
                team.WicketKipper = _playerService.GetAll().Where(p => p.Id == team.WicketKipperId).FirstOrDefault();
                team.Tournament = _tournamentService.GetAll().Where(t => t.Id == team.TournamentId).FirstOrDefault();
            }
            return View(teams);
        }
        // ------------------ Team create [HttpGet]
        public ActionResult Create()
        {
           
            List<Player> players = _playerService.GetAll();
            List<SelectListItem> playersList = players.Select(p => new SelectListItem
            {
                Value = p.Id.ToString(),
                Text = p.Name
            }).ToList();
            ViewBag.Players = players;
            List<Tournament> tournaments = _tournamentService.GetAll();
            List<SelectListItem> tournamentsList = tournaments.Select(t => new SelectListItem
            {
                Value = t.Id.ToString(),
                Text = t.Name
            }).ToList();
            ViewBag.Tournaments = tournamentsList;
            return View();
        }
        // ------------------ Team create [HttpPost]
        [HttpPost]
        public ActionResult Create(Team team, HttpPostedFileBase file, int[] selectedPlayers)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/Content/Images/Teams"), fileName);
                    file.SaveAs(path);
                    team.TeamIcon = Path.Combine("/Content/Images/Teams", fileName);
                }
                int teamId = _teamService.Add(team);
                if (teamId>0)
                {
                    _playerMatchService.Add(selectedPlayers, team.TournamentId, teamId);
                    return RedirectToAction("Index");
                }
                else
                {
                    if (team.WicketKipperId == 0)
                    {
                        ModelState.AddModelError("WicketKipper", "Wicket kippetr is required");
                    }
                    if (team.TournamentId == 0)
                    {
                        ModelState.AddModelError("Tournament", "Wicket kipper is required");
                    }
                    List<Player> players = _playerService.GetAll();
                    List<SelectListItem> playersList = players.Select(p => new SelectListItem
                    {
                        Value = p.Id.ToString(),
                        Text = p.Name
                    }).ToList();
                    ViewBag.Players = players;
                    List<Tournament> tournaments = _tournamentService.GetAll();
                    List<SelectListItem> tournamentsList = tournaments.Select(t => new SelectListItem
                    {
                        Value = t.Id.ToString(),
                        Text = t.Name
                    }).ToList();
                    ViewBag.Tournaments = tournamentsList;
                    return View(team);
                }

            }
            else
            {
                if (team.WicketKipperId == 0)
                {
                    ModelState.AddModelError("WicketKipperId", "Wicket kipper is required");
                }
                List<Player> players = _playerService.GetAll();
                List<SelectListItem> playersList = players.Select(p => new SelectListItem
                {
                    Value = p.Id.ToString(),
                    Text = p.Name
                }).ToList();
                ViewBag.Players = players;
                List<Tournament> tournaments = _tournamentService.GetAll();
                List<SelectListItem> tournamentsList = tournaments.Select(t => new SelectListItem
                {
                    Value = t.Id.ToString(),
                    Text = t.Name
                }).ToList();
                ViewBag.Tournaments = tournamentsList;
                return View(team);
            }
        }
    }
}

StumpScore/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - StumpScore</title>
    <!-- Syncfusion ASP.NET MVC controls styles -->
    <link rel="stylesheet" href="https://cdn.syncfusion.com/ej2/25.2.3/fluent.css" />
    <!-- Syncfusion ASP.NET MVC controls scripts -->
    <script src="https://cdn.syncfusion.com/ej2/25.2.3/dist/ej2.min.js"></script>
    @Styles.Render("~/Content/css")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("StumpScore", "Index", "Home", new { area = "Admin" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "Admin" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Players", "Index", "Player", new { area = "Admin" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Teams", "Index", "Team", new { area = "Admin" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Tournaments", "Index", "Tournament", new { area = "Admin" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Matches", "Index", "Match", new { area = "Admin" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    @RenderBody()
    @Html.EJS().ScriptManager()
    @RenderSection("scripts", required: false)


    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var syncfusionAd = document.querySelector('div[style*="position: fixed"][style*="top: 10px"][style*="left: 10px"][style*="right: 10px"][style*="z-index: 999999999"]');
            if (syncfusionAd) {
                syncfusionAd.remove();
            }
        });
    </script>
</body>
</html>

StumpScore/Areas/Admin/Views/Shared/_Matches.cshtml
@model List<Vispl.Trainee.StumpScore.VO.Models.Matches>

<style>
    #matchesContainer {
        margin: 3rem auto;
        display: grid;
        grid-template-columns: 60% 40%;
    }

    .tableHeading {
        background: #CDE8E5;
    }
</style>
@if (Model == null || Model.Count == 0)
{
    <p class="mt-5">There is no any sheduled matches</p>
}
else
{

    <div id="matchesContainer">
        <div>
            <table cellspacing="10" cellpadding="10" id="matchesTable">
                <thead class="tableHeading">
                    <tr>
                        <th>
                            <div>
                                Team 1
                            </div>
                        </th>
                        <th>
                            <div>
                                Team 2
                            </div>
                        </th>
                        <th>
                            <div>
                                Stadium
                            </div>
                        </th>
                        <th>
                            <div>
                                Match Start
                            </div>
                        </th>
                        <th>
                            <div>
                                Match End
                            </div>
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var match in Model)
                    {
                        <tr>
                            <td>
                                <div>
                                    @match.Team1.Name
                                </div>
                            </td>
                            <td>
                                <div>
                                    @match.Team2.Name
                                </div>
                            </td>
                            <td>
                                <div>
                                    @match.Stadium.StadiumName
                                </div>
                            </td>
                            <td>
                                <div>
                                    @match.MatchStart
                                </div>
                            </td>
                            <td>
                                <div>
                                    @match.MatchEnd
                                </div>
                            </td>
                            <td>
                                @Html.ActionLink("See Details", "MatchDetailedSummary", "Match", new { matchId = match.Id, tournamentId = match.TournamentId }, null)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="matchFilterBox">
            <p>Filter Matches</p>
            <label>From</label>
            <br />
            @Html.Partial("~\\Views\\Shared\\_DateTimeWithZone.cshtml", new string[] { "fromDateTimePicker", "fromTimeZonePicker" })
            <br />
            <label>To</label>
            <br />
            @Html.Partial("~\\Views\\Shared\\_DateTimeWithZone.cshtml", new string[] { "toDateTimePicker", "toTimeZonePicker" })
            <br />
            <button id="filterMatches">Filter</button>
        </div>
    </div>
}