StumpScore/Areas/Admin/Controllers/TournamentController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vispl.Trainee.StumpScore.BL;
using Vispl.Trainee.StumpScore.VO.Models;

namespace StumpScore.Areas.Admin.Controllers
{
    public class TournamentController : Controller
    {
        private readonly MatchFormatService _matchFormatService;
        private readonly TournamentService _tournamentService;
        public TournamentController()
        {
            _matchFormatService = new MatchFormatService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
            _tournamentService = new TournamentService(ConfigurationManager.ConnectionStrings["StumpScoreDbConnectionDEV"].ConnectionString);
        }
        // ------------------ Tournament Main page dashboard
        public ActionResult Index()
        {
            List<Tournament> tournaments = _tournamentService.GetAll();
            foreach (var tournament in tournaments)
            {
                tournament.MatchFormat = _matchFormatService.GetAll().Where(f => f.Id == tournament.MatchFormatId).FirstOrDefault();
            }
            return View(tournaments);
        }
        // ------------------ Tournament Create [HttpGet]
        public ActionResult Create()
        {
            //Tournament tournament = new Tournament();
            List<MatchFormat> matchFormats = _matchFormatService.GetAll();
            ViewBag.MatchFormats = matchFormats;
            //return View(tournament);
            return View();
        }
        // ------------------ Tournament Create [HttpPost]
        [HttpPost]
        public ActionResult Create(Tournament tournament)
        {
            if (tournament.MatchFormatId == 0)
            {
                ModelState.AddModelError("MatchFormatId", "Match format is required");
            }
            if (ModelState.IsValid)
            {
                if (_tournamentService.Add(tournament))
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    List<MatchFormat> matchFormats = _matchFormatService.GetAll();
                    ViewBag.MatchFormats = matchFormats;
                    return View(tournament);
                }
            }
            else
            {
                List<MatchFormat> matchFormats = _matchFormatService.GetAll();
                ViewBag.MatchFormats = matchFormats;
                return View(tournament);
            }
        }
    }
}

StumpScore/Areas/Admin/Views/Tournament/Create.cshtml
@model Vispl.Trainee.StumpScore.VO.Models.Tournament
@{
    ViewBag.Title = "Create Tournament";
}
<div>
    <h4 class="text-center">Create Tournament</h4>
    <div>
        @using (Html.BeginForm("Create", "Tournament", FormMethod.Post))
        {
            <div>
                @Html.LabelFor(m => m.Name)
                <span class="required">*</span>
                <br />
                @Html.EJS().TextBoxFor(m => m.Name).Placeholder("Enter the Tournament NAME").Render()
                <br/>
                @Html.ValidationMessageFor(m => m.Name, null, new {@class="text-danger"})
            </div>
            <div>
                @Html.LabelFor(m => m.ShortName)
                <span class="required">*</span>
                <br />
                @Html.EJS().TextBoxFor(m => m.ShortName).Placeholder("Enter the tournament Name in short").Render()
                <br/>
                @Html.ValidationMessageFor(m => m.ShortName, null, new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(m => m.StartingDate)
                <span class="required">*</span>
                <br />
                @Html.EJS().DatePickerFor(m => m.StartingDate).Format("dd-MM-yyyy").Placeholder("select the starting date").Render()
                <br/>
                @Html.ValidationMessageFor(m => m.StartingDate, null, new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(m => m.EndingDate)
                <span class="required">*</span>
                <br />
                @Html.EJS().DatePickerFor(m => m.EndingDate).Format("dd-MM-yyyy").Placeholder("select the ending date").Render()
                <br />
                @Html.ValidationMessageFor(m => m.EndingDate, null, new { @class = "text-danger" })
            </div>
            <div>
                @Html.LabelFor(m => m.MatchFormatId)
                <span class="required">*</span>
                <br />
                @Html.EJS().DropDownListFor(m => m.MatchFormatId).DataSource((IEnumerable<Vispl.Trainee.StumpScore.VO.Models.MatchFormat>)ViewBag.MatchFormats).Fields(f => f.Text("Name").Value("Id")).Placeholder("-- select the tournamnet format --").Render()
                <br/>
                 @Html.ValidationMessageFor(m => m.MatchFormatId, null, new {@class="text-danger"})
            </div>
            <div>
                <div>
                    <input type="submit" />
                </div>
                @*<div>
                    <a href="#">Clear</a>
                </div>*@
                <div>
                    @Html.ActionLink("go back", "Index", "Tournament", new { area = "Admin" })
                </div>
            </div>
        }
    </div>
</div>

StumpScore/Areas/Admin/Views/Tournament/Index.cshtml
@model List<Vispl.Trainee.StumpScore.VO.Models.Tournament>
@{
    ViewBag.Title = "All Tournaments";
}

<div>
    <div>
        <h2 class="text-center">All Tournaments</h2>
        @Html.ActionLink("create new", "Create", null, new { @class = "createBtn" })
    </div>
    <div>
        @Html.EJS().Grid("Grid").DataSource(Model).Columns(col =>
   {
       col.Field("Name").Add();
       col.Field("ShortName").HeaderText("Short Name").Add();
       col.Field("StartingDate").HeaderText("Starting Date").Format("dd-MM-yyyy").Add();
       col.Field("EndingDate").HeaderText("Ending Date").Format("dd-MM-yyyy").Add();
       col.Field("MatchFormat.Name").HeaderText("Format").Add();
   }).Render()
    </div>
</div>